services:
  - type: web
    name: discord-game-bot
    env: node
    plan: free
    buildCommand: "npm install"
    startCommand: "npm start"
    envVars:
      - key: BOT_TOKEN
        value: your_discord_bot_token
      - key: DB_USER
        value: your_db_user
      - key: DB_HOST
        value: your_db_host
      - key: DB_NAME
        value: your_db_name
      - key: DB_PASSWORD
        value: your_db_password
      - key: DB_PORT
        value: your_db_port
    postgresDatabases:
      - name: discord_game_bot
        user: db_user
        password: db_password
