services:
  - type: web
    name: discord-game-bot
    env: node
    plan: free
    buildCommand: "npm install"
    startCommand: PGPASSWORD=$DB_PASSWORD psql -h $DB_HOST -U $DB_USER -d $DB_NAME -f db/schema.sql && npm start
    envVars:
      - key: BOT_TOKEN
        fromDatabase: true
      - key: DB_USER
        fromDatabase: true
      - key: DB_HOST
        fromDatabase: true
      - key: DB_NAME
        fromDatabase: true
      - key: DB_PASSWORD
        fromDatabase: true
      - key: DB_PORT
        value: 5432  # Port number is typically not sensitive
